#!/usr/bin/env python3
"""Generate h2_freq.json and h2_freq.txt with MLatom + chosen reference method."""

from __future__ import annotations

import argparse
import pathlib
import sys
from typing import Any, Dict


def _best_effort_call(func: Any, kwargs: Dict[str, Any]) -> Any:
    call_kwargs = dict(kwargs)
    while True:
        try:
            return func(**call_kwargs)
        except TypeError as exc:
            message = str(exc)
            marker = "unexpected keyword argument '"
            if marker not in message:
                raise
            start = message.find(marker) + len(marker)
            end = message.find("'", start)
            if end <= start:
                raise
            bad_key = message[start:end]
            if bad_key not in call_kwargs:
                raise
            call_kwargs.pop(bad_key)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Prepare H2 equilibrium + frequency inputs.")
    parser.add_argument("--xyz", required=True)
    parser.add_argument("--freq-json-out", required=True)
    parser.add_argument("--freq-txt-out", required=True)
    parser.add_argument("--refmethod", default="B3LYP/6-31G*")
    parser.add_argument("--qmprog", default="gaussian")
    args = parser.parse_args(argv)

    import mlatom as ml  # type: ignore

    molecule_cls = ml.data.molecule if hasattr(ml, "data") else ml.molecule
    molecule = _best_effort_call(molecule_cls.from_xyz_file, {"filename": args.xyz})

    refmethod = _best_effort_call(
        ml.models.methods,
        {"method": args.refmethod, "program": args.qmprog},
    )
    eqmol = _best_effort_call(refmethod.optimize_geometry, {"molecule": molecule})
    _best_effort_call(refmethod.predict, {"molecule": eqmol, "calculate_hessian": True})

    freq_json_out = pathlib.Path(args.freq_json_out).resolve()
    freq_txt_out = pathlib.Path(args.freq_txt_out).resolve()
    freq_json_out.parent.mkdir(parents=True, exist_ok=True)
    freq_txt_out.parent.mkdir(parents=True, exist_ok=True)

    try:
        _best_effort_call(eqmol.dump, {"filename": str(freq_json_out), "format": "json"})
    except Exception:
        _best_effort_call(eqmol.dump, {"filename": str(freq_json_out)})

    atom_a = eqmol.atoms[0].xyz_coordinates
    atom_b = eqmol.atoms[1].xyz_coordinates
    dx = atom_a[0] - atom_b[0]
    dy = atom_a[1] - atom_b[1]
    dz = atom_a[2] - atom_b[2]
    bond_length = (dx * dx + dy * dy + dz * dz) ** 0.5

    frequency = eqmol.frequencies[0] if getattr(eqmol, "frequencies", None) else None
    red_mass = eqmol.reduced_masses[0] if getattr(eqmol, "reduced_masses", None) else None
    force_constant = eqmol.force_constants[0] if getattr(eqmol, "force_constants", None) else None
    zpe = getattr(eqmol, "ZPE", None)

    lines = [
        "# Generated by scripts/prepare_h2_freq.py",
        "# Units: bond_length in angstrom, frequency in cm^-1, reduced_mass in amu",
        "bond_length=%.12f" % bond_length,
        "frequency_cm-1=%s" % (str(frequency) if frequency is not None else "NA"),
        "reduced_mass_amu=%s" % (str(red_mass) if red_mass is not None else "NA"),
        "force_constant_mdyne_per_angstrom=%s"
        % (str(force_constant) if force_constant is not None else "NA"),
        "zpe_hartree=%s" % (str(zpe) if zpe is not None else "NA"),
    ]
    freq_txt_out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print("Generated:", freq_json_out)
    print("Generated:", freq_txt_out)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
